version: '2.1'
services:
  atom:
    image: pdok/atom-generator
    restart: "no"
    command: ["./atom", "-f","/inspire/xyz-localhost-example.yaml","-o","/output"]
    labels:
      nl.pdok.application.group: "atom"
    volumes:
      - ./inspire:/inspire
      - demo:/output/
    networks:
      atom-network:  
  style:
    image: pdok/atom-style
    restart: unless-stopped
    environment:
        XSLHOST: http://localhost/atom
    labels:
      nl.pdok.application.group: "style"
      SERVICE_CHECK_HTTP: "/atom/style/style.css"
      SERVICE_NAME: atom-style   
    networks:
      atom-network:            
  lighttpd:
    image: pdok/lighttpd
    restart: unless-stopped
    command: ["bash", "-c","lighttpd -D -f /srv/lighttpd/lighttpd.conf"]
    labels:
      nl.pdok.application.group: "lighttpd"
      SERVICE_CHECK_HTTP: "/"
      SERVICE_NAME: atom-style
    volumes:
      - ./lighttpd:/srv/lighttpd
      - demo:/output/download/
    networks:
      atom-network:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api=true"
      - "--api.dashboard=true"
      - "--ping=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8080"      
      - "--providers.file.directory=/config/"
    ports:
      - 80:80
      - 8080:8080
    labels:
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    volumes:
      - ./traefik/:/config/
    networks:
      atom-network:
  minio:
    image: minio/minio:RELEASE.2020-09-10T22-02-45Z
    volumes:
      - ./minio:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      atom-network:
volumes:
  demo:
networks:
  atom-network:
