---
name: lint (go)
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: setup cgo dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev libsqlite3-mod-spatialite proj-bin

      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: false

      - uses: actions/checkout@v4

      - name: Tidy
        uses: katexochen/go-tidy-check@v2

      - name: Run govulncheck (when this fails => upgrade go version)
        run: |
          GOPATH_BIN=$(go env GOPATH)/bin
          export PATH="${GOPATH_BIN}:${PATH}"
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
